nelmio_api_doc:
    documentation:
        info:
            title: ANP Auth Microservice
            description: Architecture and patterns course Auth Microservice
            version: '%api_sem_version%'
        components:
            securitySchemes:
                UserJWTBearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
                GameServiceApiToken:
                    type: apiKey
                    in: header
                    name: X-Auth-Token
    areas:
        path_patterns:
            - ^/api(?!/doc$)
