nelmio_api_doc:
    documentation:
        info:
            title: ANP Auth Microservice
            description: Architecture and patterns course Auth Microservice
            version: '%api_sem_version%'
    areas:
        path_patterns:
            - ^/api(?!/doc$)
