app.api_http_ui:
    resource:
        path: ../src//UI/Http/
        namespace: App\UI\Http
    type: attribute
    prefix: '/api/%api_version%'

app.swagger_ui:
    path: /api/%api_version%/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
