parameters:
    api_version: '%env(API_VERSION)%'
    api_sem_version: '%env(API_SEMANTIC_VERSION)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Application\UseCase\AuthUser\AuthUserUseCase:
        arguments:
            $userProvider: '@App\Application\Service\Security\UserProvider\UserProviderInterface'
            $userRefreshTokenTtl: '%env(USER_REFRESH_TOKEN_TTL)%'

    App\Infrastructure\Service\Security\UserProvider\DemoApiUserProvider:
        arguments:
            $demoUsersData:
                - { id: 1, username: joe, password: joe1234, roles: [] }
                - { id: 2, username: mary, password: mary1234, roles: [] }
